[project]
name = "kweekkast-net"
description = "Raspberry Pi responsible for network communication."
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28",
    "kweekkast-common",
    "pyserial>=3.5",
]

[project.scripts]
kweekkast-net = "kweekkast_net.main:main"

[tool.uv.sources]
kweekkast-common = { path = "../common", editable = true }

[dependency-groups]
dev = [
    "pytest>=8"
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
